version: '3.8'

services:
  mysql:
    image: mysql:8.0.32
    ports:
      - "3307:3306"
    expose:
      - 3307
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: